require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'spec/support/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/**/*'
    - 'app/concepts/**/*'

Style/SignalException:
  Exclude:
    - 'app/concepts/**/*'

RSpec/NestedGroups:
  Max: 4

RSpec/FilePath:
  Exclude:
    - 'spec/requests/*'

RSpec/MultipleExpectations:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Lint/UnreachableCode:
  Exclude:
    - 'app/concepts/**/*'
