default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: root
  password: postgres

development:
  <<: *default
  database: todo-trb_development

test:
  <<: *default
  database: todo-trb_test

production:
  <<: *default
  database: todo-trb_production
  username: todo-trb
  password: <%= ENV['TODO-TRB_DATABASE_PASSWORD'] %>
